'use client';
import { useEffect, useState } from 'react';
import { Link, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Heart, Menu, Search, Plus, Check, Play, Camera } from 'lucide-react';
import PageMotion from '../components/PageMotion';
import { Dialog, Image, Reveal } from '../components/UI';
import { pieces, instagram, bespoke, logo, journal } from './catalog';

function External({href=instagram,children,className=''}) {return <a className={className} href={href} target="_blank" rel="noreferrer">{children}</a>}
function Button({to,children,className=''}) {return <Link className={`button ${className}`} to={to}>{children}<ArrowUpRight size={17}/></Link>}
function Card({piece,saved,toggle}) {return <article className="piece-card"><div className="piece-photo"><Link to={`/product/${piece.id}`} aria-label={`Explore ${piece.name}`}><Image src={piece.image} alt={piece.name + ', styled by Veriation'} loading="lazy" width="360" height="640"/></Link><button className={`save ${saved.includes(piece.id)?'is-saved':''}`} onClick={()=>toggle(piece.id)} aria-label={`${saved.includes(piece.id)?'Remove':'Save'} ${piece.name}`} aria-pressed={saved.includes(piece.id)}><Heart size={19}/></button></div><div className="piece-info"><div><Link to={`/product/${piece.id}`}>{piece.name}</Link><p>{piece.category}</p></div><Link className="icon-button" to={`/product/${piece.id}`} aria-label={`View ${piece.name}`}><ArrowUpRight size={19}/></Link></div></article>}
function Home({saved,toggle}) {return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">VERIATION FASHION STUDIO</span><h1>Everyday.<br/><em>Extraordinary.</em></h1><p>Timeless essentials. A personal point of view.<br/>Find the pieces that feel like you.</p><Button to="/shop">Explore the edit</Button></div><div className="hero-art"><div className="hero-image-main"><Image src={pieces[3].image} alt="Veriation blush tailoring, styled with a black skirt and pink bag" fetchPriority="high" width="360" height="640"/></div><div className="hero-image-small"><Image src={pieces[5].image} alt="Veriation black halter silhouette styled by Susmita Paudyal" fetchPriority="high" width="483" height="640"/></div><span className="hero-art-word" aria-hidden="true">Veriation</span></div></section>
 <section className="edit section" id="collections"><Reveal className="section-heading"><h2>A wardrobe, <em>with feeling.</em></h2><p>The studio edit. Discover your next everyday favourite.</p></Reveal><div className="section-tools"><span>Selected by Veriation</span><Link className="text-link" to="/shop">View all pieces <ArrowUpRight size={16}/></Link></div><div className="piece-row">{pieces.slice(0,4).map((p,i)=><Reveal key={p.id} style={{'--reveal-delay':`${i*70}ms`}}><Card piece={p} saved={saved} toggle={toggle}/></Reveal>)}</div></section>
 <section className="studio section" id="studio"><Reveal className="studio-photo"><Image src={pieces[1].image} alt="Veriation studio presenting the Japandi Blouse collection" loading="lazy" width="361" height="640"/></Reveal><Reveal className="studio-copy"><h2>Different by nature.<br/><em>Personal by design.</em></h2><p>Veriation is a fashion studio curating timeless, high-quality essentials. A place to discover your style, and make it your own.</p><p>For something especially personal, explore bespoke orders with @official.kripa.</p><External href={bespoke} className="text-link">Meet your next possibility <ArrowUpRight size={18}/></External></Reveal></section>
 <section className="journal section" id="journal"><Reveal className="section-heading"><h2>Inside <em>Veriation.</em></h2><p>The people, the process, and the little details in between.</p></Reveal><div className="journal-grid">{journal.map(j=><Reveal key={j.title}><External href={j.source} className="journal-card"><div className="journal-photo"><Image src={j.image} alt={j.title} loading="lazy" width="360" height="640"/><span className="play-icon"><Play size={23} fill="currentColor"/></span></div><span className="journal-label">{j.label}</span><h3>{j.title}<ArrowUpRight size={20}/></h3></External></Reveal>)}</div></section>
 <Reveal as="section" className="bespoke section" id="bespoke"><div><span className="eyebrow">A LITTLE MORE YOU</span><h2>Your idea.<br/><em>Our next creation.</em></h2><p>Some pieces begin with a conversation.<br/>Explore a bespoke order with Kripa.</p><External href={bespoke} className="button">Start a conversation <ArrowUpRight size={18}/></External></div><Image src={pieces[0].image} alt="June Top at Veriation studio" loading="lazy" width="361" height="640"/></Reveal>
 </>}
function Shop({saved,toggle}) {const [params,setParams]=useSearchParams(); const q=params.get('q')||'';const category=params.get('category')||'All pieces';const filtered=pieces.filter(p=>(category==='All pieces'||p.category===category)&&p.name.toLowerCase().includes(q.toLowerCase()));return <section className="shop section"><h1>The studio <em>edit.</em></h1><p>Timeless essentials, styled with a little individuality.</p><div className="catalog-toolbar"><div className="filters">{['All pieces','Tops','Sets','Tailoring'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setParams({...(q?{q}:{}),...(c==='All pieces'?{}:{category:c})})}>{c}</button>)}</div><label className="search-field"><Search size={17}/><input aria-label="Search the edit" value={q} onChange={e=>setParams({q:e.target.value,...(category==='All pieces'?{}:{category})})} placeholder="Find your next piece"/></label></div><p className="results-count">{filtered.length} {filtered.length===1?'look':'looks'}</p>{filtered.length?<div className="catalog-grid">{filtered.map(p=><Card key={p.id} piece={p} saved={saved} toggle={toggle}/>)}</div>:<div className="empty"><h2>No looks found.</h2><p>Try a different search or explore the complete edit.</p><button className="button" onClick={()=>setParams({})}>See all pieces <ArrowRight size={17}/></button></div>}<p className="availability">Enquire with the studio for current prices, sizing and availability.</p></section>}
function Product({saved,toggle}) {const {slug}=useParams();const piece=pieces.find(p=>p.id===slug);if(!piece)return <NotFound/>;return <><section className="product section"><div className="product-image"><Image src={piece.image} alt={piece.name} width="360" height="640"/></div><div className="product-copy"><Link className="text-link" to="/shop">Back to the edit</Link><span className="product-category">{piece.category}</span><h1>{piece.name}</h1><p>{piece.description}</p><External className="button">Enquire with the studio <ArrowUpRight size={17}/></External><button className="outline-button" onClick={()=>toggle(piece.id)}>{saved.includes(piece.id)?<Check size={18}/>:<Plus size={18}/>} {saved.includes(piece.id)?'Saved to your edit':'Save to your edit'}</button><details><summary>How to order <Plus size={17}/></summary><p>Message @studio.veriation with the look you love. The studio will confirm pricing, available colours, fit and delivery before you order.</p></details><details><summary>Looking for something bespoke? <Plus size={17}/></summary><p>For bespoke orders, connect with @official.kripa, as listed in the studio’s Instagram bio.</p><External href={bespoke} className="text-link">Contact Kripa <ArrowUpRight size={16}/></External></details><External href={piece.source} className="text-link">See the original styling <Camera size={16}/></External></div></section><section className="section related"><h2>Another point <em>of view.</em></h2><div className="piece-row">{pieces.filter(p=>p.id!==piece.id).slice(0,4).map(p=><Card key={p.id} piece={p} saved={saved} toggle={toggle}/>)}</div></section></>}
function Saved({saved,toggle}) {const [copied,setCopied]=useState(false);const selected=pieces.filter(p=>saved.includes(p.id));async function copy(){try{await navigator.clipboard.writeText(`Hello Veriation! I’d love to know more about: ${selected.map(p=>p.name).join(', ')}. Could you share current prices, sizing and availability?`);setCopied(true)}catch{setCopied(false)}}return <section className="section saved-page"><h1>Your personal <em>edit.</em></h1><p>A little collection of the looks you love.</p>{selected.length?<><div className="catalog-grid">{selected.map(p=><Card key={p.id} piece={p} saved={saved} toggle={toggle}/>)}</div><div className="saved-actions"><p>Ready to make them yours? Copy your selection and share it with the studio.</p><button className="outline-button" onClick={copy}>{copied?<Check size={17}/>:<Plus size={17}/>} {copied?'Selection copied':'Copy enquiry'}</button><External className="button">Contact the studio <ArrowUpRight size={17}/></External><span role="status">{copied?'Your enquiry is ready to paste into Instagram.':''}</span></div></>:<div className="empty"><Heart size={30}/><h2>Something will catch your eye.</h2><p>Tap the heart on a look to save it here.</p><Button to="/shop">Discover the edit</Button></div>}</section>}
function NotFound(){return <section className="section empty"><h1>A different <em>direction.</em></h1><p>This page isn’t in the edit. Let’s find something you’ll love.</p><Button to="/shop">Back to the edit</Button></section>}
export default function Veriation(){const location=useLocation();const [menu,setMenu]=useState(false);const [search,setSearch]=useState(false);const [query,setQuery]=useState('');const [saved,setSaved]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('veriation-edit')||'[]');return Array.isArray(v)?v.filter(id=>pieces.some(p=>p.id===id)):[]}catch{return []}});
const navigate=useNavigate();
function toggle(id){setSaved(prev=>prev.includes(id)?prev.filter(v=>v!==id):[...prev,id])}
useEffect(()=>{setMenu(false);setSearch(false)},[location]);
useEffect(()=>{try{localStorage.setItem('veriation-edit',JSON.stringify(saved))}catch{}},[saved]);
useEffect(()=>{setMenu(false);setSearch(false);document.title=`${location.pathname==='/shop'?'The Studio Edit':location.pathname==='/bag'?'Your Personal Edit':'Timeless Essentials'} | Veriation`;if(location.hash){const frame=requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));return ()=>cancelAnimationFrame(frame)}else window.scrollTo({top:0,behavior:'instant'});},[location.pathname,location.hash]);
return <PageMotion><a className="skip-link" href="#main">Skip to content</a><header className="header"><nav aria-label="Main navigation"><Link to="/shop">The edit</Link><Link to="/#studio">Our studio</Link><Link to="/#bespoke">Bespoke</Link></nav><button className="icon-button mobile-menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu size={21}/></button><Link to="/" className="brand-logo" aria-label="Veriation home"><img src={logo} alt="Veriation Fashion Studio" width="150" height="150"/></Link><div className="header-actions"><button className="icon-button" aria-label="Search" onClick={()=>setSearch(true)}><Search size={19}/></button><Link className="saved-link" to="/bag" aria-label={`Your edit, ${saved.length} saved looks`}><Heart size={19}/><span>Your edit</span><span>({saved.length})</span></Link></div></header><main id="main" tabIndex={-1}><Routes><Route path="/" element={<Home saved={saved} toggle={toggle}/>}/><Route path="/shop" element={<Shop saved={saved} toggle={toggle}/>}/><Route path="/product/:slug" element={<Product saved={saved} toggle={toggle}/>}/><Route path="/bag" element={<Saved saved={saved} toggle={toggle}/>}/><Route path="*" element={<NotFound/>}/></Routes></main><footer className="footer section"><div className="footer-top"><div><Link to="/" className="footer-name">Veriation</Link><p>Timeless essentials.<br/>Endlessly personal.</p></div><nav aria-label="Footer navigation"><Link to="/shop">Explore the edit</Link><Link to="/#studio">Our studio</Link><Link to="/#bespoke">Bespoke orders</Link><External>Instagram <ArrowUpRight size={14}/></External></nav><div className="footer-social"><p>Wear it your way.</p><External className="text-link">@studio.veriation <ArrowUpRight size={17}/></External><span>#studioveriation</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Veriation Studio</span><span>Made for your everyday.</span><a href="#main" className="text-link">Back to top <ArrowUpRight size={15}/></a></div></footer><Dialog open={menu} onDismiss={()=>setMenu(false)} title="Explore Veriation"><nav className="menu-links"><Link to="/shop">The edit <ArrowUpRight/></Link><Link to="/#studio">Our studio <ArrowUpRight/></Link><Link to="/#bespoke">Bespoke <ArrowUpRight/></Link><Link to="/bag">Your personal edit <Heart/></Link></nav></Dialog><Dialog open={search} onDismiss={()=>setSearch(false)} title="Something catch your eye?"><form className="search-form" onSubmit={e=>{e.preventDefault();navigate(`/shop?q=${encodeURIComponent(query)}`)}}><label className="search-field"><Search size={18}/><input autoFocus aria-label="Search looks" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try June or Japandi"/></label><Button to={`/shop?q=${encodeURIComponent(query)}`}>Search the edit</Button></form></Dialog></PageMotion>}


